import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Book } from '../models/book';

@Injectable({
  providedIn: 'root',
})
export class BookService {
  books: Array<Book> = [
    {
      id: 1,
      title: 'Business Services',
      author: 'Ailis Collier',
      resume: 'Vision-oriented high-level core',
      genre: 'Documentary',
      year: 1978,
      isbn: '120558557-5',
      description: 'envisioneer wireless niches',
      rating: 4.6,
      price: 51.58,
      cover: './assets/img/covers/1.png',
    },
    {
      id: 2,
      title: 'Major Banks',
      author: 'Debora Loosely',
      resume: 'Enhanced holistic task-force',
      genre: 'Comedy',
      year: 1990,
      isbn: '016353034-3',
      description: 'implement synergistic systems',
      rating: 3.7,
      price: 32.86,
      cover: './assets/img/covers/2.png',
    },
    {
      id: 3,
      title: 'Glorious Foresights of the Abyssal Lexicon',
      author: 'Tedman Clemerson',
      resume: 'Front-line support',
      genre: 'Action|Comedy|Crime',
      year: 2006,
      isbn: '654664013-9',
      description: 'Streamlined attitude-oriented software',
      rating: 2.7,
      price: 57.05,
      cover: './assets/img/covers/3.png',
    },
    {
      id: 4,
      title: 'Computer Software: Prepackaged Software',
      author: 'Josephine Jobin',
      resume: 'Organic secondary local area network',
      genre: 'Comedy|Drama|Romance',
      year: 2011,
      isbn: '439976533-X',
      description: 'engage magnetic web services',
      rating: 2.1,
      price: 68.53,
      cover: './assets/img/covers/4.png',
    },
    {
      id: 5,
      title: 'Metal Fabrications',
      author: 'Dill Sandle',
      resume: 'Configurable neutral frame',
      genre: 'Documentary|IMAX',
      year: 1985,
      isbn: '843575075-2',
      description: 'orchestrate proactive platforms',
      rating: 1.2,
      price: 9.83,
      cover: './assets/img/covers/5.png',
    },
    {
      id: 6,
      title: 'Telecommunications Equipment',
      author: 'Christy Bonnar',
      resume: 'Expanded clear-thinking capacity',
      genre: 'Thriller',
      year: 1981,
      isbn: '432019048-3',
      description: 'mesh strategic technologies',
      rating: 4.1,
      price: 76.89,
      cover: './assets/img/covers/6.png',
    },
    {
      id: 7,
      title: 'Tai Chi Sword Handling',
      author: 'Boycey Giovanetti',
      resume: 'Open-source secondary adapter',
      genre: 'Adventure',
      year: 2002,
      isbn: '739863758-6',
      description: 'deliver bricks-and-clicks supply-chains',
      rating: 1.1,
      price: 79.25,
      cover: './assets/img/covers/7.png',
    },
    {
      id: 8,
      title: 'Marine Transportation',
      author: 'Mei Gandar',
      resume: 'Adaptive explicit portal',
      genre: 'Comedy|Drama',
      year: 2021,
      isbn: '093542328-1',
      description: 'aggregate mission-critical e-commerce',
      rating: 4.0,
      price: 44.91,
      cover: './assets/img/covers/8.png',
    },
    {
      id: 9,
      title: 'Business Services',
      author: 'Darci Kunert',
      resume: 'Fundamental executive capacity',
      genre: 'Drama',
      year: 1987,
      isbn: '888096998-6',
      description: 'maximize innovative interfaces',
      rating: 1.5,
      price: 111.24,
      cover: './assets/img/covers/9.png',
    },
    {
      id: 10,
      title: 'Biotechnology: Laboratory Analytical Instruments',
      author: 'Lemur Desantis',
      resume: 'cultivate real-time architectures',
      genre: 'Drama',
      year: 1989,
      isbn: '062713887-X',
      description: 'Exclusive demand-driven methodology',
      rating: 4.9,
      price: 97.45,
      cover: './assets/img/covers/10.png',
    },
    {
      id: 11,
      title: 'Collected Dicta of Divinity',
      author: 'Billy Bambery',
      resume: 'Focused multimedia algorithm',
      genre: 'Adventure|Children|Fantasy',
      year: 2020,
      isbn: '915346473-7',
      description: 'mesh distributed initiatives',
      rating: 1.1,
      price: 107.87,
      cover: './assets/img/covers/11.png',
    },
    {
      id: 12,
      title: 'Experiential Theorems on Searching',
      author: 'Bram Egalton',
      resume: 'Persevering global knowledge user',
      genre: 'Drama|Romance',
      year: 1981,
      isbn: '355395864-2',
      description: 'enable holistic metrics',
      rating: 3.1,
      price: 65.03,
      cover: './assets/img/covers/12.png',
    },
    {
      id: 13,
      title: 'Other Consumer Services',
      author: 'Lillian Andrus',
      resume: 'Ameliorated 4th generation budgetary management',
      genre: 'Action|Adventure|Children|Comedy|Sci-Fi',
      year: 1980,
      isbn: '861113003-0',
      description: 'enhance value-added action-items',
      rating: 2.0,
      price: 44.15,
      cover: './assets/img/covers/13.png',
    },
    {
      id: 14,
      title: 'Telecommunications Equipment',
      author: 'Blakelee MacElane',
      resume: 'Team-oriented asynchronous frame',
      genre: 'Crime|Drama|Film-Noir|Mystery',
      year: 1973,
      isbn: '809856971-3',
      description: 'leverage revolutionary content',
      rating: 4.4,
      price: 61.91,
      cover: './assets/img/covers/14.png',
    },
    {
      id: 15,
      title: 'Major Banks',
      author: 'Fidole Castledine',
      resume: 'Open-source upward-trending product',
      genre: 'Fantasy|Horror|Thriller',
      year: 1977,
      isbn: '204453109-7',
      description: 'clickable architectures',
      rating: 4.8,
      price: 34.91,
      cover: './assets/img/covers/15.png',
    },
    {
      id: 16,
      title: 'Finance: Consumer Services',
      author: 'Kynthia Moughtin',
      resume: 'Switchable bi-directional moderator',
      genre: 'Drama|Film-Noir',
      year: 1990,
      isbn: '727603117-9',
      description: 'recontextualize proactive e-tailers',
      rating: 4.5,
      price: 96.62,
      cover: './assets/img/covers/16.png',
    },
    {
      id: 17,
      title: 'Lessons on the Children of the Saddle',
      author: 'Blanca Dunkerly',
      resume: 'Implemented stable attitude',
      genre: 'Comedy|Documentary',
      year: 1995,
      isbn: '304844968-X',
      description: 'architect global metrics',
      rating: 2.6,
      price: 107.53,
      cover: './assets/img/covers/17.png',
    },
    {
      id: 18,
      title: 'Real Estate Investment Trusts',
      author: 'Perkin MacPhail',
      resume: 'Expanded 24 hour methodology',
      genre: 'Comedy',
      year: 2009,
      isbn: '811185462-5',
      description: 'synergize cross-media e-markets',
      rating: 3.2,
      price: 51.49,
      cover: './assets/img/covers/18.png',
    },
    {
      id: 19,
      title: 'Containers/Packaging',
      author: 'Carce Capel',
      resume: 'Future-proofed intangible throughput',
      genre: 'Drama|Romance|War',
      year: 2008,
      isbn: '945808783-X',
      description: 'scale proactive partnerships',
      rating: 4.3,
      price: 21.67,
      cover: './assets/img/covers/19.png',
    },
    {
      id: 20,
      title: 'Assimilated asymmetric moratorium',
      author: 'Desiri Hethron',
      resume: 'Total bifurcated website',
      genre: 'Comedy|Drama',
      year: 1989,
      isbn: '620375992-9',
      description: 'Up-sized leading edge pricing structure',
      rating: 3.1,
      price: 99.57,
      cover: './assets/img/covers/20.png',
    },
  ];

  constructor() {}

  getAllBooks(): Observable<Book[]> {
    return of(this.books);
  }
}
